logging.level:
  org.springframework: info
    #transaction: info
    #security: trace
    #context.support.ResourceBundleMessageSource: DEBUG

spring:
  messages:
    basename: fw-messages,application-messages
    encoding: UTF-8
  profiles:
    group:
      jpa-all: item-jpa,reservation-jpa,user-jpa
      file-all: item-file,reservation-file,user-file
    default: jpa-all
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      javax.persistence.validation.mode: NONE
  mvc:
    format:
      date: yyyyMMdd
      date-time: yyyyMMdd HH:mm

management:
  info:
    java.enabled: true
    os.enabled: true
    process.enabled: true    
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: "readinessState,db,dependentServers"
      validate-group-membership: false # groupにindicatorが存在しない場合もエラーにしない設定

rms:
  log:
    server:
      enable: false
  jwt-encode:
    enable: true
    private-key: classpath:/jwt.key
    clock:
      type: SYSTEM
      fixed-datetime: 2024-01-01T12:30 # typeがSYSTEMの場合は無視される
    claim:
      issuer: JsonWebTokenIntegrationTest
      exp: 60                 # 有効期限（分単位）
  jwt-deencode:
    public-key: classpath:/jwt.pub.key
    claim:
      issuer: ${rms.jwt-encode.claim.issuer}
  health:
    depend-services:
      - http://localhost:8081/actuator/health/readiness
  rest:
    controller:
      format:
        date: ${spring.mvc.format.date}
        date-time: ${spring.mvc.format.date-time}
  persistence:
    item:
      csv:
        type: temporary
        temporary:
          resource: temporary/itemTemp.csv
      sql:
        schema-locations: classpath:sql/item-schema.sql
        data-locations: classpath:sql/item-data.sql
      remote:
        url: http://localhost:${local.server.port}/remote
        format:
          date: ${spring.mvc.format.date}
          date-time: ${spring.mvc.format.date-time}
    reservation:
      csv:
        type: temporary
        temporary:
          resource: temporary/reservationTemp.csv
      sql:
        schema-locations: classpath:sql/reservation-schema.sql
        data-locations: classpath:sql/reservation-data.sql
      remote:
        url: http://localhost:${local.server.port}/remote
        format:
          date: ${spring.mvc.format.date}
          date-time: ${spring.mvc.format.date-time}
    user:
      csv:
        type: temporary
        temporary:
          resource: temporary/userTemp.csv
      sql:
        schema-locations: classpath:sql/user-schema.sql
        data-locations: classpath:sql/user-data.sql
      remote:
        url: http://localhost:${local.server.port}/remote
        format:
          date: ${spring.mvc.format.date}
          date-time: ${spring.mvc.format.date-time}
