logging.level:
  org.springframework:
    #transaction: info
    #security: trace

spring:
  messages:
    basename: application-messages
    encoding: UTF-8
  profiles:
    default: item-jpa,reservation-jpa,user-jpa
  sql:
    init:
      schema-locations: classpath:sql/item-schema.sql,sql/user-schema.sql,sql/reservation-schema.sql
      data-locations: classpath:sql/item-data.sql,sql/user-data.sql,sql/reservation-data.sql
  jpa:
    open-in-view:
      false
    hibernate:
      ddl-auto: none
    properties:
      javax.persistence.validation.mode: NONE

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: "readinessState,db"
      validate-group-membership: false # groupにindicatorが存在しない場合もエラーにしない設定

rms:
  debug:
    configdump:
      enable: false
      #system-properties: on
      #system-environment: on
  log:
    server:
      enable: false
  persistence:
    item:
      csv:
        type: temporary
        temporary:
          resource: temporary/itemTemp.csv
    reservation:
      csv:
        type: temporary
        temporary:
          resource: temporary/reservationTemp.csv
    user:
      csv:
        type: temporary
        temporary:
          resource: temporary/userTemp.csv
