DELETE FROM ITEM_ENTITY;

INSERT INTO ITEM_ENTITY VALUES (1, 'A0001', '便利なパソコン');
INSERT INTO ITEM_ENTITY VALUES (2, 'DSP001', '映りが良い液晶ディスプレイ');
INSERT INTO ITEM_ENTITY VALUES (3, 'CX000A012', '握り抜群マウス');
INSERT INTO ITEM_ENTITY VALUES (4, 'KJJ4763', 'REALFORCEのステキなキーボード');
INSERT INTO ITEM_ENTITY VALUES (5, 'AO10DDDA', '激安ノートパソコン');
INSERT INTO ITEM_ENTITY VALUES (6, 'SHOE0000001', '空飛べるスゴイ靴');
INSERT INTO ITEM_ENTITY VALUES (7, 'RENTAL0001', 'レンタル品1号');
INSERT INTO ITEM_ENTITY VALUES (8, 'ELBG00001', 'エルメスのお高いバック');
