CREATE SEQUENCE IF NOT EXISTS RESERVATION_SEQ START WITH 1000 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS RESERVATION_ENTITY (
    ID INT PRIMARY KEY,
    FROM_DATE_TIME TIMESTAMP NOT NULL,
    TO_DATE_TIME TIMESTAMP NOT NULL,
    NOTE VARCHAR(192),
    ITEM_ID INT NOT NULL,
    RESERVER_ID INT NOT NULL
);
