CREATE SEQUENCE IF NOT EXISTS USER_SEQ START WITH 1000 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS USER_ENTITY (
    ID INT PRIMARY KEY,
    LOGIN_ID VARCHAR(10) NOT NULL,
    PASSWORD VARCHAR(10) NOT NULL,
    USER_NAME VARCHAR(48) NOT NULL,
    PHONE_NUMBER VARCHAR(14),
    CONTACT VARCHAR(120),
    USER_TYPE VARCHAR(15) NOT NULL
);
